name: phi_env
channels:
  - conda-forge
  - defaults
dependencies:
  - esmf=8.4.1#mpi_mpich
  - esmpy=8.4.1#mpi_mpich  
  - adlfs=0.7.7
  - aiohttp=3.7.4
  - cartopy=0.21.1
  - dask=2024.1.1 #=2021.6.2
  - dask-gateway=2024.1.0 #=0.9.0
  - dask-labextension=5.0.2
  - fsspec=2021.9.0
  - geopandas=0.13.2 
  - geos=3.11.1
  - h5py=3.7.0
  - imbalanced-learn=0.10.1
  - importlib_resources=6.0.0
  - intake=0.6.2
  - intake-xarray=0.5.0
  - ipywidgets=7.6.3
  - joblib=1.2
  - libnetcdf=4.9.1
  - matplotlib=3.4.3  
  - metpy=0.12.2  
  - netcdf4=1.6.2
  - nco=5.1.5
  - numcodecs=0.12.1 #=0.8.0
  - numpy=1.22.4
  - pip=23.3.2 #=22.0.3
  - pyarrow=10.0.1  
  - pygrib=2.1.4
  - pyresample=1.26.1
  - pyyaml=5.4.1
  - s3fs=2021.9.0
  - scikit-image=0.19.1
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2023.0.1
  - sharppy=1.4.0
  - tqdm=4.64.1
  - wrf-python=1.3.4.1
  - xarray=0.21.1
  - xesmf=0.8.2
  - pynio=1.5.5
  - zarr=2.11.0
  - pip:
    - tensorflow==2.15.0
    - xgboost==1.7.1
    - hyperopt==0.2.7 
    - monte-python>=2.0.3942 #==1.1.901
    - pint==0.19 # Metpy breaks with "No module named 'pint.unit'" on 0.20, 0.21
    - pysolar
    - wofs-ml-severe>=1.1.4395
    - ml-workflow>=1.1.4343
    - jax==0.4.24
    - jaxlib==0.4.24
    - scikit-explain 
    - mlw2w
  - python=3.10
#  - basemap-data-hires=1.2.2
